In [94]:
import numpy as np
import pandas as pd

In [95]:
traindata=pd.read_csv("/train (1).csv")
testdata=pd.read_csv("/test (1).csv")
target=pd.read_csv("/gender_submission.csv")

In [96]:
target=target["Survived"]
t=np.array(target)
t=t.T
t.shape

(418,)

In [99]:
traindata
traindata['Age'].fillna(traindata['Age'].mean(), inplace=True)

In [100]:
ytrain=traindata["Survived"]
xtrain=traindata.drop(["Pclass","Cabin","Embarked","Name","Ticket","PassengerId"],axis=1)
xtest=testdata.drop(["Pclass","Cabin","Embarked","Name","Ticket","PassengerId"],axis=1)
xtest

Sex   Age  SibSp  Parch      Fare
0      male  34.5      0      0    7.8292
1    female  47.0      1      0    7.0000
2      male  62.0      0      0    9.6875
3      male  27.0      0      0    8.6625
4    female  22.0      1      1   12.2875
..      ...   ...    ...    ...       ...
413    male   NaN      0      0    8.0500
414  female  39.0      0      0  108.9000
415    male  38.5      0      0    7.2500
416    male   NaN      0      0    8.0500
417    male   NaN      1      1   22.3583

[418 rows x 5 columns]

In [101]:
xtrain["Sex"].unique()
Gender={"male":1, "female":0}
xtrain=xtrain.replace(Gender)
xtest=xtest.replace(Gender)
xtrain

Survived  Sex        Age  SibSp  Parch     Fare
0           0    1  22.000000      1      0   7.2500
1           1    0  38.000000      1      0  71.2833
2           1    0  26.000000      0      0   7.9250
3           1    0  35.000000      1      0  53.1000
4           0    1  35.000000      0      0   8.0500
..        ...  ...        ...    ...    ...      ...
886         0    1  27.000000      0      0  13.0000
887         1    0  19.000000      0      0  30.0000
888         0    0  29.699118      1      2  23.4500
889         1    1  26.000000      0      0  30.0000
890         0    1  32.000000      0      0   7.7500

[891 rows x 6 columns]

In [102]:
def sigmoid(z):
    s = 1/(1 + np.exp(-z)) 
    # s[np.isnan(s)] = np.nanmean(s)
    return s

In [103]:
def loss(h,y):
  return(-(y*np.log(h)+(1-y)*np.log(1-h)))

In [104]:
def forward(w,x,b):
  c=np.dot(w.T,x)+b
  c[np.isnan(c)] = np.nanmean(c)
  return c

In [105]:
def gradient(x,h,y):
  return (np.dot(x,(h-y).T)/x.shape[1])

In [106]:
def const(h,y):
   n=(np.sum(h-y))/x.shape[1]
   return n

In [107]:
def gradeint(x,lr,iter,w,b,y):
  for i in range(iter):
    z=forward(w,x,b)
   
    # z=np.nan_to_num(z, nan=np.nanmean(z))
    a=sigmoid(z)
  
    # a=np.nan_to_num(a, nan=np.nanmean(a))
    los=loss(a,y)
    
    # los=np.nan_to_num(los, nan=np.nanmean(los))
    cost=(np.sum(los))/x.shape[1]
    dz=np.dot(a,y)
    
    dw=gradient(x,a,y)
   
    db=const(a,y)
    
    w=w-lr*dw
    w[np.isnan(w)] = np.nanmean(w)
    b=b-lr*db
    
    if (i%5==0):
      print ("Cost after iteration %i: %f" %(i, cost))
 

In [108]:
xtrain = (xtrain - np.min(xtrain)) / (np.max(xtrain) - np.min(xtrain)).values
xtest=(xtest - np.min(xtest)) / (np.max(xtest) - np.min(xtest)).values

In [109]:
x=np.array(xtrain)
x=x.T
x.shape


(6, 891)

In [110]:
xt=np.array(xtest)
xt=xt.T
xt.shape

(5, 418)

In [111]:
y=np.array(ytrain)
y=y.T
y.shape
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [112]:
# w=np.zeros((x.shape[1],1))
# print(w.shape)
# w
w = np.full((x.shape[0],1),0.02)
w.shape
w

array([[0.02],
       [0.02],
       [0.02],
       [0.02],
       [0.02],
       [0.02]])

In [113]:
wt = np.full((xt.shape[0],1),0.02)
wt.shape
wt

array([[0.02],
       [0.02],
       [0.02],
       [0.02],
       [0.02]])

In [114]:
b=0.0

In [115]:
fit(x,0.0001,900,w,b,y)

Cost after iteration 0: 0.694587
Cost after iteration 5: 0.694539
Cost after iteration 10: 0.694491
Cost after iteration 15: 0.694443
Cost after iteration 20: 0.694394
Cost after iteration 25: 0.694346
Cost after iteration 30: 0.694298
Cost after iteration 35: 0.694250
Cost after iteration 40: 0.694202
Cost after iteration 45: 0.694153
Cost after iteration 50: 0.694105
Cost after iteration 55: 0.694057
Cost after iteration 60: 0.694009
Cost after iteration 65: 0.693961
Cost after iteration 70: 0.693913
Cost after iteration 75: 0.693865
Cost after iteration 80: 0.693817
Cost after iteration 85: 0.693768
Cost after iteration 90: 0.693720
Cost after iteration 95: 0.693672
Cost after iteration 100: 0.693624
Cost after iteration 105: 0.693576
Cost after iteration 110: 0.693528
Cost after iteration 115: 0.693480
Cost after iteration 120: 0.693432
Cost after iteration 125: 0.693384
Cost after iteration 130: 0.693336
Cost after iteration 135: 0.693288
Cost after iteration 140: 0.693240
Cost af

In [116]:
def predict(w,b,x_test):
    # x_test is a input for forward propagation
    z = sigmoid(np.dot(w.T,x_test)+b)
    Y_prediction = np.zeros((1,x_test.shape[1]))
    # if z is bigger than 0.5, our prediction is one means has diabete (y_head=1),
    # if z is smaller than 0.5, our prediction is zero means does not have diabete (y_head=0),
    for i in range(z.shape[1]):
        if z[0,i]< 0.60:
            Y_prediction[0,i] = 0
        else:
            Y_prediction[0,i] = 1

    return Y_prediction

In [117]:
y_prediction=predict(wt,b,xt)
y_prediction.shape

(1, 418)

In [118]:
print("test accuracy: {} %".format(100 - np.mean(np.abs(y_prediction - t)) * 100))

test accuracy: 54.78468899521531 %


In [119]:
A=[1,20,0,0,7.5]
S=[0,19,1,1,512]
ar=np.array(A)
sh=np.array(S)
ar=ar.reshape(5,1)
sh=sh.reshape(5,1)
ar.shape

(5, 1)

In [120]:
wa= np.random.rand(ar.shape[0],1)
ws=np.random.rand(sh.shape[0],1)
wa

array([[0.63994093],
       [0.9448422 ],
       [0.52256257],
       [0.91489553],
       [0.94817498]])

Arpit Survived


In [122]:
ypreds=predict(ws,b,sh)
if(ypreds):
  print("Shreya Survived")
else:
  print("Shreya Not Survived")

Shreya Survived
